apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://172.30.89.131:6443
    k8sVersion: v1.13.5
    path: default
kind: ksonnet.io/app
libraries:
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: 430d4f7ae16af389ac570182af519f6571f160cf
name: object-detection-app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
